apiVersion: batch/v1
kind: Job
metadata:
  name: $JOBID
spec:
  completions: $NUM_TASKS
  parallelism: $NUM_TASKS
  template:
    metadata:
      name: $JOBID
    spec:
      containers:
      - name: c
        image: sv440/sv440:job-wq
        env:
        - name: REDIS_SERVICE_HOST
          value: "10.102.79.76"
        - name: JOBID
          value: "$JOBID"
      imagePullSecrets:
      - name: regcred
      restartPolicy: OnFailure
